name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential
      run: sudo apt install valgrind

    - name: Compile the program
      working-directory: src
      run: make

    - name: Run tests
      working-directory: src
      run: valgrind ./main 10
